# -*- coding: utf-8 -*-
"""01_etl_sih.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tf3DK3rHyJekuTdI-BYmxJkG_vIDuLae

## Fonte: SIH-SUS (Sistema de Informações Hospitalares)

O SIH-SUS registra todas as internações hospitalares financiadas pelo SUS,
via Autorização de Internação Hospitalar (AIH). É a fonte primária do projeto
porque contém as variáveis que compõem a variável-alvo:

- `MORTE` → óbito durante a internação (base do numerador da letalidade)
- `DIAG_PRINC` → CID-10 do diagnóstico principal (filtra DRSAI)
- `MUNIC_RES` → município de residência (unidade de análise)
- `VAL_TOT` → valor total da AIH (extensão futura: custo-evitabilidade)

**Decisão metodológica:** usamos município de *residência* (`MUNIC_RES`),
não de internação, para medir o risco da população local e não a concentração
de hospitais nas capitais.
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls /content/drive/MyDrive/projeto_drsai

!ls /content/drive/MyDrive/projeto_drsai/data/raw/sih

# ============================================================
# CÉLULA 1 — Instalar PySUS (versão mais recente do GitHub)
# Execute e depois: Runtime → Restart runtime
# ============================================================

!pip install pysus==1.0.1

import pysus
print(f"PySUS instalado e rodando! Versão: {pysus.__version__}")

from pysus import SIH
sih = SIH().load()
print("Sucesso! Base do SIH carregada.")

# ============================================================
# CÉLULA 3 — Imports e configuração de paths
# (adaptação da Seção 1 para o Colab)
# ============================================================
import gc
import time
import logging
from pathlib import Path
from datetime import timedelta

import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa

# Verifica versões
assert pd.__version__ >= "1.5"
assert pa.__version__ >= "10.0"

# --- Paths no Google Drive ---
PATH_BASE    = Path('/content/drive/MyDrive/projeto_drsai')
DATA_RAW     = PATH_BASE / 'data' / 'raw' / 'sih'
DATA_INTERIM = PATH_BASE / 'data' / 'interim' / 'sih_drsai'
DATA_PROCESSED = PATH_BASE / 'data' / 'processed'
LOG_PATH     = PATH_BASE / 'pipeline_sih.log'

# Cria estrutura de pastas no Drive
for pasta in [DATA_RAW, DATA_INTERIM, DATA_PROCESSED]:
    pasta.mkdir(parents=True, exist_ok=True)

# --- Logging (arquivo no Drive + console) ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    datefmt='%H:%M:%S',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_PATH),
    ]
)
log = logging.getLogger(__name__)

# --- Constantes do projeto ---
ANOS_BASELINE  = [2017, 2018, 2019]
ANOS_MODELAGEM = [2023, 2024]
ANOS_TODOS     = ANOS_BASELINE + ANOS_MODELAGEM
MESES          = list(range(1, 13))

UFS_BR = [
    'AC','AL','AP','AM','BA','CE','DF','ES','GO',
    'MA','MT','MS','MG','PA','PB','PR','PE','PI',
    'RJ','RN','RS','RO','RR','SC','SP','SE','TO',
]

PREFIXOS_DRSAI_V2 = {
    'fecal_oral': [
        'A00','A01','A02','A03','A04','A05',
        'A06','A07','A08','A09','B15'
    ],
    'leptospirose': ['A27'],
    'helmintiase': [
        'B65','B66','B67','B68','B69','B70',
        'B71','B72','B73','B74','B75','B76',
        'B77','B78','B79','B80','B81','B82','B83'
    ],
    'arboviral': ['A90','A91','A92'],
    'malaria':   ['B50','B51','B52','B53','B54'],
}
TODOS_PREFIXOS_V2 = {
    p for lista in PREFIXOS_DRSAI_V2.values() for p in lista
}

def categorizar_drsai_v2(cid: str) -> str:
    if not isinstance(cid, str) or len(cid) < 3:
        return 'fora_escopo'
    prefixo = cid[:3]
    for categoria, lista in PREFIXOS_DRSAI_V2.items():
        if prefixo in lista:
            return categoria
    return 'fora_escopo'

COLUNAS_SIH = [
    'ANO_CMPT','MES_CMPT','DT_INTER','DT_SAIDA',
    'MUNIC_RES','UF_ZI',
    'DIAG_PRINC','DIAG_SECUN','MORTE',
    'IDADE','COD_IDADE','SEXO','RACA_COR',
    'DIAS_PERM','VAL_TOT','UTI_MES_TO',
    'N_AIH',
]

log.info('Configuração OK')
print(f'✅ Paths configurados em: {PATH_BASE}')
print(f'   Anos: {ANOS_TODOS} | UFs: {len(UFS_BR)} | Arquivos: {len(ANOS_TODOS)*12*27}')

# ============================================================
# CÉLULA 4 — Funções utilitárias
# (exatamente as mesmas do notebook local — sem alteração)
# ============================================================

def categorizar_drsai(cid: str) -> str:
    if not isinstance(cid, str) or len(cid) < 3:
        return 'fora_escopo'
    prefixo = cid[:3]
    for categoria, lista in PREFIXOS_DRSAI.items():
        if prefixo in lista:
            return categoria
    return 'fora_escopo'


def normalizar_tipos_sih(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if 'MORTE' in df.columns:
        df['MORTE'] = (pd.to_numeric(df['MORTE'], errors='coerce')
                         .fillna(0).astype('int8'))
    for col in ['SEXO','RACA_COR','COD_IDADE']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int8')
    for col in ['IDADE','DIAS_PERM','UTI_MES_TO','ANO_CMPT','MES_CMPT']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int32')
    if 'VAL_TOT' in df.columns:
        df['VAL_TOT'] = pd.to_numeric(df['VAL_TOT'], errors='coerce')
    for col in ['DT_INTER','DT_SAIDA']:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], format='%Y%m%d', errors='coerce')
    for col in ['DIAG_PRINC','DIAG_SECUN','MUNIC_RES','UF_ZI','N_AIH']:
        if col in df.columns:
            df[col] = df[col].astype('string')
    return df


def arquivo_valido(caminho: Path) -> bool:
    if not caminho.exists():
        return False
    try:
        pq.read_schema(caminho)
        return True
    except Exception:
        return False


def baixar_e_ler_sih(uf: str, ano: int, mes: int,
                     pasta_destino: Path) -> pd.DataFrame:
    pasta_destino.mkdir(parents=True, exist_ok=True)
    try:
        from pysus.ftp.databases.sih import SIH
        sih = SIH().load()
        arquivos_meta = sih.get_files(group='RD', uf=uf, year=ano, month=mes)
        if not arquivos_meta:
            raise FileNotFoundError(f'Sem arquivos RD: {uf} {ano}-{mes:02d}')
        parquet_set = sih.download(arquivos_meta, local_dir=str(pasta_destino))
        if isinstance(parquet_set, list):
            parquet_set = parquet_set[0]
        df = pq.read_table(parquet_set.path, columns=COLUNAS_SIH).to_pandas()
    except (ImportError, AttributeError):
        from pysus.online_data import SIH
        sih = SIH()
        parquet_set = sih.download(
            states=[uf], years=[ano], months=[mes], groups=['RD']
        )
        if isinstance(parquet_set, list):
            parquet_set = parquet_set[0]
        df = pq.read_table(parquet_set.path, columns=COLUNAS_SIH).to_pandas()
    return normalizar_tipos_sih(df)

print('✅ Funções carregadas')

# ============================================================
# CÉLULA 5 — Smoke test (AC/2024-06 — arquivo pequeno)
# Valida que PySUS + Drive estão funcionando antes do download
# ============================================================
log.info('Rodando smoke test...')
df_teste = baixar_e_ler_sih('AC', 2024, 6, DATA_RAW / 'spike')
cats = df_teste['DIAG_PRINC'].apply(categorizar_drsai)
n_drsai = (cats != 'fora_escopo').sum()

assert df_teste['MORTE'].dtype == 'int8', 'Bug de tipo em MORTE'
assert 50 <= n_drsai <= 200, f'DRSAI fora da faixa: {n_drsai}'

print(f'✅ Smoke test OK: {len(df_teste):,} linhas, {n_drsai} DRSAI')
print(f'   Arquivo salvo em: {DATA_RAW}/spike/')
del df_teste, cats
gc.collect()

# ============================================================
# CÉLULA 6 — Download em massa (Seção 2)
# ATENÇÃO: ~6 horas na primeira rodada
# Idempotente: pode ser interrompido e retomado
# ============================================================

def baixar_arquivo_sih_bruto(uf: str, ano: int, mes: int) -> str:
    pasta_ano = DATA_RAW / str(ano)
    pasta_ano.mkdir(parents=True, exist_ok=True)
    nome = f'sih_rd_{uf}_{ano}_{mes:02d}.parquet'
    caminho = pasta_ano / nome

    if caminho.exists() and arquivo_valido(caminho):
        return 'ja_valido'
    elif caminho.exists():
        caminho.unlink()
        status_base = 'redownload'
    else:
        status_base = 'baixado'

    try:
        df = baixar_e_ler_sih(uf, ano, mes, DATA_RAW / '_tmp')
        df.to_parquet(caminho, index=False, compression='snappy')
        del df
        gc.collect()
        return status_base
    except FileNotFoundError:
        return 'nao_encontrado'
    except Exception as e:
        log.error(f'Erro {uf}/{ano}-{mes:02d}: {type(e).__name__}: {e}')
        return f'erro:{type(e).__name__}'


def executar_download_massa() -> dict:
    contadores = {'ja_valido':0,'baixado':0,'redownload':0,
                  'nao_encontrado':0,'erro':0}
    total = len(ANOS_TODOS) * len(MESES) * len(UFS_BR)
    processados = 0
    inicio = time.time()
    log.info(f'Iniciando download: {total} arquivos')

    for ano in ANOS_TODOS:
        for mes in MESES:
            for uf in UFS_BR:
                processados += 1
                status = baixar_arquivo_sih_bruto(uf, ano, mes)
                chave = status if ':' not in status else 'erro'
                contadores[chave] = contadores.get(chave, 0) + 1

                if processados % 50 == 0 or 'erro' in status:
                    elapsed = time.time() - inicio
                    eta = str(timedelta(seconds=int(
                        (total - processados) / max(processados/elapsed, 0.01)
                    )))
                    log.info(
                        f'[{processados}/{total}] '
                        f'✅{contadores["baixado"]} '
                        f'⏭️{contadores["ja_valido"]} '
                        f'❌{contadores["erro"]} '
                        f'| ETA: {eta} | {uf}/{ano}-{mes:02d} → {status}'
                    )

    log.info('DOWNLOAD CONCLUÍDO')
    log.info(f'Baixados: {contadores["baixado"]} | '
             f'Já existiam: {contadores["ja_valido"]} | '
             f'Erros: {contadores["erro"]}')
    return contadores


print('✅ Função de download pronta.')
print('   Rode: resultado = executar_download_massa()')

# CÉLULA DE EXECUÇÃO
resultado = executar_download_massa()

# ============================================================
# SEÇÃO 3 — Filtro DRSAI arquivo por arquivo
# Lê bruto → filtra DRSAI → salva interim
# Tempo estimado: 30-60 minutos
# Idempotente: pode ser interrompido e retomado
# ============================================================

def processar_arquivo_drsai(uf: str, ano: int, mes: int) -> str:
    pasta_interim_ano = DATA_INTERIM / str(ano)
    pasta_interim_ano.mkdir(parents=True, exist_ok=True)
    caminho_interim = pasta_interim_ano / f'sih_drsai_{uf}_{ano}_{mes:02d}.parquet'
    caminho_bruto   = DATA_RAW / str(ano) / f'sih_rd_{uf}_{ano}_{mes:02d}.parquet'

    if caminho_interim.exists() and arquivo_valido(caminho_interim):
        return 'ja_processado'
    if not caminho_bruto.exists():
        return 'bruto_ausente'

    try:
        df = pq.read_table(caminho_bruto, columns=COLUNAS_SIH).to_pandas()
        df = normalizar_tipos_sih(df)
        df['categoria_drsai'] = df['DIAG_PRINC'].apply(categorizar_drsai)
        df_drsai = df[df['categoria_drsai'] != 'fora_escopo'].copy()
        df_drsai.to_parquet(caminho_interim, index=False, compression='snappy')
        status = 'sem_drsai' if len(df_drsai) == 0 else 'processado'
        del df, df_drsai
        gc.collect()
        return status
    except Exception as e:
        log.error(f'Erro filtro {uf}/{ano}-{mes:02d}: {type(e).__name__}: {e}')
        return f'erro:{type(e).__name__}'


def executar_filtro_drsai() -> dict:
    contadores = {'ja_processado':0,'processado':0,
                  'sem_drsai':0,'bruto_ausente':0,'erro':0}
    total = len(ANOS_TODOS) * len(MESES) * len(UFS_BR)
    processados = 0
    inicio = time.time()

    log.info(f'Iniciando filtro DRSAI: {total} arquivos')

    for ano in ANOS_TODOS:
        for mes in MESES:
            for uf in UFS_BR:
                processados += 1
                status = processar_arquivo_drsai(uf, ano, mes)
                chave = status if ':' not in status else 'erro'
                contadores[chave] = contadores.get(chave, 0) + 1

                if processados % 100 == 0 or 'erro' in status:
                    elapsed = time.time() - inicio
                    eta = str(timedelta(seconds=int(
                        (total - processados) / max(processados/elapsed, 0.01)
                    )))
                    log.info(
                        f'[{processados}/{total}] '
                        f'✅{contadores["processado"]} '
                        f'⏭️{contadores["ja_processado"]} '
                        f'❌{contadores["erro"]} '
                        f'| ETA: {eta} | {uf}/{ano}-{mes:02d} → {status}'
                    )

    log.info('=' * 60)
    log.info('FILTRO CONCLUÍDO')
    log.info(f'Processados:    {contadores["processado"]:>5}')
    log.info(f'Já existiam:    {contadores["ja_processado"]:>5}')
    log.info(f'Sem DRSAI:      {contadores["sem_drsai"]:>5}')
    log.info(f'Brutos ausentes:{contadores["bruto_ausente"]:>5}')
    log.info(f'Erros:          {contadores["erro"]:>5}')
    return contadores

print('✅ Função de filtro pronta. Execute:')
print('   resultado_filtro = executar_filtro_drsai()')

resultado_filtro = executar_filtro_drsai()

import subprocess

# Conta quantos arquivos interim já foram gerados
result = subprocess.run(
    ['find', str(DATA_INTERIM), '-name', '*.parquet', '-type', 'f'],
    capture_output=True, text=True
)
arquivos = result.stdout.strip().split('\n') if result.stdout.strip() else []
print(f"Arquivos interim já gerados: {len(arquivos)}")

# Mostra os 5 mais recentes
if arquivos:
    print("\nÚltimos arquivos criados:")
    for a in sorted(arquivos)[-5:]:
        print(f"  {a.split('/')[-1]}")

# 1. Verifica o conteúdo da variável resultado_filtro
print("=== Resultado do filtro ===")
print(resultado_filtro)
print()

# 2. Conta os arquivos interim que existem de fato
import subprocess
result = subprocess.run(
    ['find', str(DATA_INTERIM), '-name', '*.parquet', '-type', 'f'],
    capture_output=True, text=True
)
arquivos_interim = result.stdout.strip().split('\n') if result.stdout.strip() else []
print(f"=== Interim no Drive ===")
print(f"Arquivos .parquet: {len(arquivos_interim)}")

# 3. Conta os arquivos brutos para comparar
result_raw = subprocess.run(
    ['find', str(DATA_RAW), '-name', '*.parquet', '-type', 'f'],
    capture_output=True, text=True
)
arquivos_raw = [a for a in result_raw.stdout.strip().split('\n')
                if a and 'spike' not in a and '_tmp' not in a]
print(f"=== Brutos no Drive ===")
print(f"Arquivos .parquet: {len(arquivos_raw)}")

# 4. Mostra o log se existir
print(f"\n=== Últimas linhas do log ===")
result_log = subprocess.run(
    ['tail', '-30', str(LOG_PATH)],
    capture_output=True, text=True
)
print(result_log.stdout)

# Validação do interim — sanity check epidemiológico
import pandas as pd

AMOSTRAS_VALIDACAO = [
    ("SP", 2017, 1),    # mesma do spike
    ("PE", 2019, 7),    # mesma do spike
    ("RS", 2023, 10),   # mesma do spike
    ("AC", 2024, 6),    # mesma do spike
]

print("=== Validação do interim (regressão vs spike) ===\n")

for uf, ano, mes in AMOSTRAS_VALIDACAO:
    caminho = DATA_INTERIM / str(ano) / f"sih_drsai_{uf}_{ano}_{mes:02d}.parquet"

    if not caminho.exists():
        print(f"❌ {uf}/{ano}-{mes:02d}: arquivo não encontrado")
        continue

    df = pd.read_parquet(caminho)
    n = len(df)
    obitos = (df["MORTE"] == 1).sum() if n > 0 else 0
    let = round(100 * obitos / n, 2) if n > 0 else 0
    cats = df["categoria_drsai"].value_counts().to_dict() if n > 0 else {}

    print(f"{uf}/{ano}-{mes:02d}: {n:>5} DRSAI | "
          f"letalidade {let:>5}% | {cats}")

