# -*- coding: utf-8 -*-
"""04_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHCI2RDk8y_IYCgTznC2MgUNSVP-1OWo
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', palette='muted', font_scale=1.1)
plt.rcParams['figure.dpi'] = 130

PATH_PARQUET = '/content/drive/MyDrive/projeto_drsai/data/processed/analitico_municipio_mes.parquet'

df = pd.read_parquet(PATH_PARQUET)

print(f'✅ Dataset carregado: {df.shape[0]:,} linhas × {df.shape[1]} colunas')
print(f'   Período       : {df["ANO_CMPT"].min()} – {df["ANO_CMPT"].max()}')
print(f'   Municípios    : {df["MUNIC_RES"].nunique():,}')
print(f'   Macrorregiões : {df["cod_macrorregiao"].nunique()}')
print(f'\nColunas disponíveis: {list(df.columns)}')

print('=' * 60)
print('TIPOS DE DADOS E VALORES NULOS')
print('=' * 60)

info = pd.DataFrame({
    'dtype':    df.dtypes,
    'nulos':    df.isna().sum(),
    'pct_nulo': (df.isna().mean() * 100).round(2),
    'únicos':   df.nunique()
})
print(info.to_string())

COLS_NUMERICAS = [c for c in [
    'n_internacoes_drsai', 'n_obitos_drsai', 'letalidade_drsai',
    'idade_media', 'permanencia_media', 'valor_total_drsai',
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    'indice_atendimento_total_agua', 'indice_coleta_esgoto',
    'indice_tratamento_esgoto', 'indice_perda_distribuicao_agua',
    'indice_esgotamento_agua_consumida',
] if c in df.columns]

desc = df[COLS_NUMERICAS].describe(percentiles=[.25, .50, .75, .95]).T
desc['cv'] = (desc['std'] / desc['mean']).round(3)

pd.set_option('display.float_format', '{:.3f}'.format)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 130)
print('ESTATÍSTICA DESCRITIVA (CV = std/média — quanto maior, mais assimétrica):')
print(desc.to_string())

print('=' * 55)
print('DIAGNÓSTICO: n_obitos_drsai')
print('=' * 55)

n_zero = (df['n_obitos_drsai'] == 0).sum()
n_pos  = (df['n_obitos_drsai'] >  0).sum()
total  = len(df)

print(f'  Total de linhas       : {total:>10,}')
print(f'  Linhas com 0 óbitos   : {n_zero:>10,}  ({100*n_zero/total:.1f}%)')
print(f'  Linhas com >= 1 óbito : {n_pos:>10,}  ({100*n_pos/total:.1f}%)')
print(f'  Máximo                : {df["n_obitos_drsai"].max()}')
print(f'  Mediana geral         : {df["n_obitos_drsai"].median():.2f}')
print(f'  Mediana (apenas >0)   : {df[df["n_obitos_drsai"]>0]["n_obitos_drsai"].median():.2f}')
print(f'  Média                 : {df["n_obitos_drsai"].mean():.4f}')
print(f'  Desvio padrão         : {df["n_obitos_drsai"].std():.4f}')
print(f'\n  Valores mais frequentes:')
print(df['n_obitos_drsai'].value_counts().head(10).to_string())

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Painel 1 — pizza zeros vs positivos
axes[0].pie(
    [n_zero, n_pos],
    labels=['0 óbitos\n(sem evento)', '>=1 óbito\n(evento ocorreu)'],
    autopct='%1.1f%%',
    colors=['#AED6F1', '#E74C3C'],
    startangle=90
)
axes[0].set_title('Proporção Zeros vs Positivos', fontweight='bold')

# Painel 2 — histograma apenas positivos (até p99)
obitos_pos = df[df['n_obitos_drsai'] > 0]['n_obitos_drsai']
p99 = obitos_pos.quantile(0.99)
axes[1].hist(obitos_pos[obitos_pos <= p99], bins=30,
             color='#E74C3C', edgecolor='white', linewidth=0.5)
axes[1].axvline(obitos_pos.median(), color='navy', linestyle='--',
                label=f'Mediana: {obitos_pos.median():.0f}')
axes[1].axvline(obitos_pos.mean(), color='orange', linestyle='-.',
                label=f'Média: {obitos_pos.mean():.2f}')
axes[1].set_title('Distribuição (apenas >0, até p99)', fontweight='bold')
axes[1].set_xlabel('n_obitos_drsai')
axes[1].set_ylabel('Frequência')
axes[1].legend()

# Painel 3 — boxplot por ano (positivos)
df_pos_df = df[df['n_obitos_drsai'] > 0]
anos_ord  = sorted(df_pos_df['ANO_CMPT'].unique())
dados_box = [df_pos_df[df_pos_df['ANO_CMPT']==a]['n_obitos_drsai'].clip(upper=p99) for a in anos_ord]
axes[2].boxplot(dados_box, labels=anos_ord, patch_artist=True,
                boxprops=dict(facecolor='#AED6F1'))
axes[2].set_title('Distribuição por Ano (positivos, até p99)', fontweight='bold')
axes[2].set_xlabel('Ano')
axes[2].set_ylabel('n_obitos_drsai')

fig.suptitle('Análise da Variável Target: n_obitos_drsai', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/projeto_drsai/eda_01_target.png', dpi=150, bbox_inches='tight')
plt.show()
print('Salvo: eda_01_target.png')

df_baseline = df[df['ANO_CMPT'].isin([2017, 2018, 2019])]
mu    = df_baseline['n_obitos_drsai'].mean()
sigma = df_baseline['n_obitos_drsai'].std()

print(f'Baseline 2017–2019: µ = {mu:.4f} | σ = {sigma:.4f}')
print()
print(f'{"k1":>6} {"k2":>6} | {"Limiar Médio":>14} {"Limiar Alto":>12} | {"% Baixo":>8} {"% Médio":>8} {"% Alto":>8}')
print('-' * 78)

resultados_thresh = []
for k1 in [0.1, 0.25, 0.5, 0.75]:
    for k2 in [0.5, 0.75, 1.0, 1.5]:
        if k2 <= k1:
            continue
        lm = mu + k1 * sigma
        la = mu + k2 * sigma
        labels = df['n_obitos_drsai'].apply(
            lambda x: 2 if x >= la else (1 if x >= lm else 0)
        )
        dist    = labels.value_counts(normalize=True)
        p_baixo = dist.get(0, 0)
        p_medio = dist.get(1, 0)
        p_alto  = dist.get(2, 0)
        resultados_thresh.append((k1, k2, lm, la, p_baixo, p_medio, p_alto))
        flag = '  <- CANDIDATO' if p_medio >= 0.03 and p_alto >= 0.02 else ''
        print(f'{k1:>6.2f} {k2:>6.2f} | {lm:>14.4f} {la:>12.4f} | {p_baixo:>7.1%} {p_medio:>8.1%} {p_alto:>8.1%}{flag}')

# Visualiza distribuição de classes para cada par candidato
candidatos = [(r[0], r[1]) for r in resultados_thresh if r[5] >= 0.03 and r[6] >= 0.02]

if candidatos:
    n_cand = min(len(candidatos), 4)
    fig, axes = plt.subplots(1, n_cand, figsize=(4 * n_cand, 4))
    if n_cand == 1:
        axes = [axes]

    cores_bar = ['#3498DB', '#F39C12', '#E74C3C']
    for ax, (k1, k2) in zip(axes, candidatos[:4]):
        lm = mu + k1 * sigma
        la = mu + k2 * sigma
        labels = df['n_obitos_drsai'].apply(
            lambda x: 2 if x >= la else (1 if x >= lm else 0)
        )
        counts = labels.value_counts().sort_index()
        bars = ax.bar(['Baixo', 'Médio', 'Alto'],
                      [counts.get(0,0), counts.get(1,0), counts.get(2,0)],
                      color=cores_bar)
        ax.set_title(f'k1={k1}, k2={k2}\nLm={lm:.3f} | La={la:.3f}',
                     fontsize=9, fontweight='bold')
        ax.set_ylabel('Frequência')
        for bar in bars:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., h,
                    f'{h:,.0f}\n({100*h/len(df):.1f}%)',
                    ha='center', va='bottom', fontsize=8)

    fig.suptitle('Distribuição de Classes por Par (k1, k2) — Threshold µ + k*σ', fontweight='bold')
    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/projeto_drsai/eda_02_calibracao_threshold.png',
                dpi=150, bbox_inches='tight')
    plt.show()
    print('Salvo: eda_02_calibracao_threshold.png')
else:
    print('ATENÇÃO: Nenhum par candidato encontrado com >= 3% Médio e >= 2% Alto.')
    print('Considere a abordagem por percentil na célula abaixo.')

# Alternativa: thresholds por percentil (garante proporções controladas)
print('THRESHOLDS POR PERCENTIL (alternativa ao µ + k*σ):')
print()
for p1, p2 in [(70, 90), (60, 85), (50, 80)]:
    lm = df_baseline['n_obitos_drsai'].quantile(p1/100)
    la = df_baseline['n_obitos_drsai'].quantile(p2/100)
    labels = df['n_obitos_drsai'].apply(
        lambda x: 2 if x >= la else (1 if x >= lm else 0)
    )
    dist = labels.value_counts(normalize=True)
    print(f'  p{p1}/p{p2}: Lm={lm:.3f} | La={la:.3f} | '
          f'Baixo={dist.get(0,0):.1%}  Médio={dist.get(1,0):.1%}  Alto={dist.get(2,0):.1%}')

# Diagnóstico primeiro — veja a distribuição real dos valores positivos
df_pos = df[df['n_obitos_drsai'] > 0]

print("Distribuição dos valores positivos:")
print(df_pos['n_obitos_drsai'].value_counts().sort_index().head(15))
print()
print(f"Percentis dos positivos:")
for p in [25, 50, 75, 90, 95]:
    print(f"  p{p}: {df_pos['n_obitos_drsai'].quantile(p/100):.0f}")

# Thresholds inteiros — únicos que fazem sentido para variável de contagem
# Baixo  = 0 óbitos       (sem evento)
# Médio  = 1 óbito        (evento isolado)
# Alto   = >= 2 óbitos    (evento recorrente / severo)

df['risco_ternario'] = df['n_obitos_drsai'].apply(
    lambda x: 0 if x == 0 else (1 if x == 1 else 2)
)

dist = df['risco_ternario'].value_counts(normalize=True).sort_index()
print("Distribuição com threshold inteiro (0 / 1 / >=2):")
print(f"  Baixo (0 óbitos) : {dist.get(0,0):.1%}")
print(f"  Médio (1 óbito)  : {dist.get(1,0):.1%}")
print(f"  Alto  (>=2)      : {dist.get(2,0):.1%}")

# Classifica risco SOMENTE entre os municípios com pelo menos 1 óbito
# usando os percentis da distribuição dos positivos no baseline

df_baseline_pos = df_baseline[df_baseline['n_obitos_drsai'] > 0]
p66 = df_baseline_pos['n_obitos_drsai'].quantile(0.66)
p90 = df_baseline_pos['n_obitos_drsai'].quantile(0.90)

print(f"Limiar Médio→Alto (p66 dos positivos): {p66:.0f}")
print(f"Limiar Alto       (p90 dos positivos): {p90:.0f}")

def classificar(x):
    if x == 0:
        return 0          # Baixo — sem evento
    elif x <= p66:
        return 1          # Médio — evento leve
    else:
        return 2          # Alto  — evento severo

df['risco_ternario'] = df['n_obitos_drsai'].apply(classificar)
print(df['risco_ternario'].value_counts(normalize=True).sort_index())

"""Macrorregião x letalidade"""

# Agrega para macrorregião × trimestre — unidade analítica real do projeto
df['trimestre'] = ((df['MES_CMPT'] - 1) // 3) + 1

df_macro_tri = (
    df.groupby(['cod_macrorregiao', 'nome_macrorregiao', 'ANO_CMPT', 'trimestre'])
    .agg(
        n_obitos_drsai       = ('n_obitos_drsai',       'sum'),
        n_internacoes_drsai  = ('n_internacoes_drsai',  'sum'),
        fecal_oral           = ('fecal_oral',            'sum'),
        leptospirose         = ('leptospirose',          'sum'),
        helmintiase          = ('helmintiase',           'sum'),
        arboviral            = ('arboviral',             'sum'),
        malaria              = ('malaria',               'sum'),
        idade_media          = ('idade_media',           'mean'),
        permanencia_media    = ('permanencia_media',     'mean'),
        indice_coleta_esgoto              = ('indice_coleta_esgoto',              'mean'),
        indice_atendimento_total_agua     = ('indice_atendimento_total_agua',     'mean'),
        indice_tratamento_esgoto          = ('indice_tratamento_esgoto',          'mean'),
        indice_perda_distribuicao_agua    = ('indice_perda_distribuicao_agua',    'mean'),
        indice_esgotamento_agua_consumida = ('indice_esgotamento_agua_consumida', 'mean'),
    )
    .reset_index()
)

print(f"Shape após agregação: {df_macro_tri.shape}")
print(f"\nEstatísticas de n_obitos_drsai (macrorregião × trimestre):")
print(df_macro_tri['n_obitos_drsai'].describe(percentiles=[.25,.50,.75,.90,.95]))
print(f"\nZeros: {(df_macro_tri['n_obitos_drsai']==0).mean():.1%}")
print(f"Distribuição dos valores positivos:")
print(df_macro_tri[df_macro_tri['n_obitos_drsai']>0]['n_obitos_drsai']
      .value_counts().sort_index().head(50))

# ── TARGET BINÁRIO ────────────────────────────────────────────────────────────
# 0 = nenhum óbito DRSAI nesse município/mês
# 1 = pelo menos 1 óbito DRSAI nesse município/mês

df['houve_obito'] = (df['n_obitos_drsai'] >= 1).astype(int)

print("Distribuição do target:")
print(df['houve_obito'].value_counts(normalize=True)
      .rename({0:'Sem óbito (0)', 1:'Com óbito (1)'}))

# ── FEATURES ──────────────────────────────────────────────────────────────────
# Regra: nenhuma feature pode usar informação do mesmo período do target
# n_internacoes_drsai está no mesmo mês — risco de leakage se muito correlacionado
# Verifique a correlação antes de incluir

FEATURES = [
    # Perfil epidemiológico do município no mês
    'n_internacoes_drsai',
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    'idade_media', 'permanencia_media',
    # Saneamento municipal (SNIS — anual, sem leakage)
    'indice_atendimento_total_agua',
    'indice_coleta_esgoto',
    'indice_tratamento_esgoto',
    'indice_perda_distribuicao_agua',
    'indice_esgotamento_agua_consumida',
    # Temporalidade
    'MES_CMPT',
]
FEATURES = [f for f in FEATURES if f in df.columns]

df_modelo = df[FEATURES + ['houve_obito']].dropna()

print(f"\nShape do dataset de modelagem: {df_modelo.shape}")
print(f"Features: {len(FEATURES)}")