# -*- coding: utf-8 -*-
"""05_mineracao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siEFp724r13PzADijGSO4J80RC-DG8nJ

NOTEBOOK 05 — MINERAÇÃO: CLASSIFICAÇÃO BINÁRIA

Treinar uma Regressão Logística Binária para prever se
houve óbito DRSAI num município em determinado mês.
- Unidade analítica : município × mês
- Target            : houve_obito (n_obitos_drsai >= 1)
- Treino            : 2017–2019 (padrão histórico pré-pandemia)
- Teste             : 2023–2024 (avaliação em dados futuros)
- Excluído          : 2020–2022 (choque COVID)
- Imbalance         : class_weight='balanced'
- Métrica principal : Macro F1-Score

ENTRADA : analitico_municipio_mes.parquet (output notebook 04)
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_auc_score,
    RocCurveDisplay,
    f1_score,
)

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams['figure.dpi'] = 130

PATH_PARQUET  = '/content/drive/MyDrive/projeto_drsai/data/processed/analitico_municipio_mes.parquet'
PATH_OUTPUTS  = '/content/drive/MyDrive/projeto_drsai/'

df = pd.read_parquet(PATH_PARQUET)
print(f'✅ Dataset carregado: {df.shape[0]:,} linhas × {df.shape[1]} colunas')
print(f'   Anos disponíveis: {sorted(df["ANO_CMPT"].unique())}')

# ── TARGET BINÁRIO ────────────────────────────────────────────────────────────
df['houve_obito'] = (df['n_obitos_drsai'] >= 1).astype(int)

print('Distribuição do target (dataset completo):')
print(df['houve_obito'].value_counts(normalize=True)
      .rename({0: 'Sem óbito (0)', 1: 'Com óbito (1)'}))

# ── FEATURES ─────────────────────────────────────────────────────────────────
FEATURES = [f for f in [
    'n_internacoes_drsai',
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    'idade_media', 'permanencia_media',
    'indice_atendimento_total_agua',
    'indice_coleta_esgoto',
    'indice_tratamento_esgoto',
    'indice_perda_distribuicao_agua',
    'indice_esgotamento_agua_consumida',
    'MES_CMPT',
] if f in df.columns]

print(f'\nFeatures selecionadas ({len(FEATURES)}): {FEATURES}')

# ── DATASET DE MODELAGEM (remove nulos) ───────────────────────────────────────
df_modelo = df[FEATURES + ['houve_obito', 'ANO_CMPT']].dropna()
print(f'\nShape após remover nulos: {df_modelo.shape[0]:,} linhas')

# ── SPLIT TEMPORAL ────────────────────────────────────────────────────────────
# Treina com padrão histórico pré-pandemia, avalia em dados recentes
# Isso simula o uso real: treinar no passado para prever o futuro

df_treino = df_modelo[df_modelo['ANO_CMPT'].isin([2017, 2018, 2019])]
df_teste  = df_modelo[df_modelo['ANO_CMPT'].isin([2023, 2024])]

X_train = df_treino[FEATURES]
y_train = df_treino['houve_obito']

X_test  = df_teste[FEATURES]
y_test  = df_teste['houve_obito']

print('Split temporal:')
print(f'  Treino (2017–2019): {len(X_train):>7,} linhas')
print(f'  Teste  (2023–2024): {len(X_test):>7,} linhas')
print()
print('Distribuição do target no treino:')
print(y_train.value_counts(normalize=True).rename({0:'Sem óbito', 1:'Com óbito'}))
print()
print('Distribuição do target no teste:')
print(y_test.value_counts(normalize=True).rename({0:'Sem óbito', 1:'Com óbito'}))

# ESCALONAMENTO
# µ — Média (soma dos valores / qtd de observações)
# σ — Desvio padrão (mede o quanto os valores se afastam da média
# (grau de dispersão))

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)   # aprende µ e σ do treino
X_test_sc  = scaler.transform(X_test)        # aplica os mesmos µ e σ

print('Escalonamento aplicado:')
for i, feat in enumerate(FEATURES):
    print(f'  {feat:<42}  µ={scaler.mean_[i]:>8.3f}  σ={scaler.scale_[i]:>8.3f}')

# TREINAMENTO
# class_weight='balanced': penaliza proporcionalmente os erros na classe
# minoritária (Com óbito = 6.5%), evitando que o modelo preveja sempre 0
# solver='lbfgs': recomendado para datasets médios com regularização L2

model = LogisticRegression(
    class_weight='balanced',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)

model.fit(X_train_sc, y_train)
print('Modelo treinado.')
print(f'Iterações até convergência: {model.n_iter_[0]}')

"""### Conceitos
- Support: quantas amostras reais existem de cada classe no conjunto de teste.
```
Sem Óbito (0) → support = 64.482  (municípios que realmente não tiveram óbito)
Com Óbito (1) → support =  5.850  (municípios que realmente tiveram óbito)
Total          →           70.33
```
- Precision: de tudo que o modelo previu como positivo, o que REALMENTE é positivo? (se é falso positivo ou não)\
Precision = VP / (VP + FP)
```
Com Óbito (1) → Precision = 0.16

Significa: de cada 100 municípios que o modelo classificou como
"com óbito", apenas 16 realmente tiveram óbito.
Os outros 84 foram falsos alarmes.
```
- Recall: de todos os positivos reais, quantos o modelo conseguiu detectar de verdade\
Recall = VP / (VP + FN)
```
Com Óbito (1) → Recall = 0.75

Significa: de cada 100 municípios que realmente tiveram óbito,
o modelo detectou 75.
Os outros 25 passaram despercebidos (falsos negativos).
```
- F1-score: média harmônica entre recall e precision.\
F1 = 2 * [(Precision * Recall) / (Precision + Recall)]
```
Com Óbito (1) → F1 = 2 × (0.16 × 0.75) / (0.16 + 0.75) = 0.27

O F1 baixo (0.27) revela que o modelo está desequilibrado:
recall alto (75%) mas precision muito baixa (16%).
```


"""

# PREDIÇÃO
y_pred  = model.predict(X_test_sc)
y_proba = model.predict_proba(X_test_sc)[:, 1] # P(houve_obito=1)

# MÉTRICAS
print('=' * 55)
print('AVALIAÇÃO DO MODELO — CONJUNTO DE TESTE (2023–2024)')
print('=' * 55)

print('\nRelatório de Classificação:')
print(classification_report(
    y_test, y_pred,
    target_names=['Sem Óbito (0)', 'Com Óbito (1)']
))

macro_f1 = f1_score(y_test, y_pred, average='macro')
auc      = roc_auc_score(y_test, y_proba)

print(f'Macro F1-Score : {macro_f1:.4f}  ← métrica principal')
print(f'AUC-ROC        : {auc:.4f}')

# VISUALIZAÇÕES
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Matriz de confusão
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=['Sem Óbito', 'Com Óbito'])
disp.plot(ax=axes[0], cmap='Blues', colorbar=False)
axes[0].set_title('Matriz de Confusão\n(Teste 2023–2024)', fontweight='bold')

# Curva ROC
RocCurveDisplay.from_predictions(
    y_test, y_proba, ax=axes[1],
    name=f'Regressão Logística (AUC={auc:.3f})',
    color='#2471A3'
)
axes[1].plot([0,1],[0,1], 'k--', linewidth=1, label='Aleatório (AUC=0.500)')
axes[1].set_title('Curva ROC\n(Teste 2023–2024)', fontweight='bold')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig(PATH_OUTPUTS + 'mineracao_01_confusao_roc.png', dpi=150, bbox_inches='tight')
plt.show()
print('Salvo: mineracao_01_confusao_roc.png')

# COEFICIENTES E ODDS RATIO
# Odds Ratio = e^coef
# OR > 1: aumenta a chance de óbito
# OR < 1: reduz a chance de óbito
# OR = 1: sem efeito

coef_df = pd.DataFrame({
    'feature':     FEATURES,
    'coeficiente': model.coef_[0],
    'odds_ratio':  np.exp(model.coef_[0])
}).sort_values('odds_ratio', ascending=False)

print('COEFICIENTES DO MODELO (ordenado por Odds Ratio):')
print()
print(f'{"Feature":<42} {"Coef":>8} {"Odds Ratio":>12}  Direção')
print('-' * 75)
for _, row in coef_df.iterrows():
    direcao = '▲ aumenta risco' if row['odds_ratio'] > 1 else '▼ reduz risco'
    print(f'{row["feature"]:<42} {row["coeficiente"]:>8.4f} {row["odds_ratio"]:>12.4f}  {direcao}')

print()
print('Intercepto:', round(model.intercept_[0], 4))

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

cores = ['#E74C3C' if v > 1 else '#2ECC71' for v in coef_df['odds_ratio']]

# Painel 1 — Odds Ratio
axes[0].barh(coef_df['feature'], coef_df['odds_ratio'], color=cores)
axes[0].axvline(1.0, color='black', linestyle='--', linewidth=1.2, label='OR = 1 (sem efeito)')
axes[0].set_xlabel('Odds Ratio')
axes[0].set_title('Odds Ratio por Feature\n(vermelho=aumenta risco | verde=reduz risco)',
                  fontweight='bold')
axes[0].legend(fontsize=8)

# Painel 2 — Coeficientes brutos
cores_coef = ['#E74C3C' if v > 0 else '#2ECC71' for v in coef_df['coeficiente']]
axes[1].barh(coef_df['feature'], coef_df['coeficiente'], color=cores_coef)
axes[1].axvline(0, color='black', linestyle='--', linewidth=1.2)
axes[1].set_xlabel('Coeficiente')
axes[1].set_title('Coeficientes Brutos\n(positivo=aumenta risco | negativo=reduz risco)',
                  fontweight='bold')

plt.tight_layout()
plt.savefig(PATH_OUTPUTS + 'mineracao_02_coeficientes.png', dpi=150, bbox_inches='tight')
plt.show()
print('Salvo: mineracao_02_coeficientes.png')

# RESUMO
print('=' * 60)
print('RESUMO — REGRESSÃO LOGÍSTICA BINÁRIA | DRSAI')
print('=' * 60)

tn, fp, fn, tp = cm.ravel()
precision_1 = tp / (tp + fp) if (tp + fp) > 0 else 0
recall_1    = tp / (tp + fn) if (tp + fn) > 0 else 0

print(f"""
DESIGN
  Algoritmo      : Regressão Logística Binária
  Unidade        : Município × Mês
  Target         : houve_obito (n_obitos_drsai >= 1)
  Treino         : 2017–2019  ({len(X_train):,} linhas)
  Teste          : 2023–2024  ({len(X_test):,} linhas)
  Imbalance      : class_weight='balanced'

MÉTRICAS (Teste 2023–2024)
  Macro F1-Score : {macro_f1:.4f}
  AUC-ROC        : {auc:.4f}
  Precision (1)  : {precision_1:.4f}  → dos previstos como risco, {precision_1:.1%} realmente são
  Recall    (1)  : {recall_1:.4f}  → dos casos reais de risco, {recall_1:.1%} foram capturados

MATRIZ DE CONFUSÃO
  Verdadeiro Negativo (TN) : {tn:>7,}  (sem óbito, previsto corretamente)
  Falso Positivo     (FP) : {fp:>7,}  (sem óbito, previsto como risco)
  Falso Negativo     (FN) : {fn:>7,}  (com óbito, NÃO detectado) ← crítico
  Verdadeiro Positivo (TP) : {tp:>7,}  (com óbito, detectado corretamente)

TOP 3 FEATURES QUE MAIS AUMENTAM RISCO:""")

for _, row in coef_df[coef_df['odds_ratio'] > 1].head(3).iterrows():
    print(f'  {row["feature"]:<42} OR = {row["odds_ratio"]:.3f}')

print(f"""
TOP 3 FEATURES QUE MAIS REDUZEM RISCO:""")
for _, row in coef_df[coef_df['odds_ratio'] < 1].tail(3).iterrows():
    print(f'  {row["feature"]:<42} OR = {row["odds_ratio"]:.3f}')

print()
print('=' * 60)

# DIAGNÓSTICO 2: VIF (Variance Inflation Factor)
# VIF > 5 indica multicolinearidade preocupante
# VIF > 10 é grave

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif = pd.DataFrame({
    'feature': FEATURES,
    'VIF': [variance_inflation_factor(X_train_sc, i) for i in range(X_train_sc.shape[1])]
}).sort_values('VIF', ascending=False)

print('Variance Inflation Factor (multicolinearidade):')
print(vif.to_string(index=False))
print()
print('Regra: VIF > 5 → multicolinearidade | VIF > 10 → grave')

# ── DIAGNÓSTICO 3: confirmar correlação saneamento × tamanho do município ────
print('Correlação entre saneamento e volume de internações:')
print(f'  coleta_esgoto vs n_internacoes  : {X_train["indice_coleta_esgoto"].corr(X_train["n_internacoes_drsai"]):.3f}')
print(f'  trat_esgoto   vs n_internacoes  : {X_train["indice_tratamento_esgoto"].corr(X_train["n_internacoes_drsai"]):.3f}')
print(f'  agua          vs n_internacoes  : {X_train["indice_atendimento_total_agua"].corr(X_train["n_internacoes_drsai"]):.3f}')

# Se essas correlações forem altas (>0.3), confirma que municípios com mais
# saneamento têm mais internações por terem mais infraestrutura

"""# Versão 2

FEATURES CORRIGIDAS
Removidas:
   - n_internacoes_drsai → é a soma das categorias (colinearidade quase perfeita)
   - indice_esgotamento_agua_consumida → redundante com coleta+tratamento (r=0.74/0.80)

 Justificativa metodológica: ao manter as 5 categorias separadas, o modelo pode
 pesar diferentemente cada uma. Ao manter coleta+tratamento separados, distinguimos infraestrutura de coleta (passiva) de tratamento (ativa).
"""

FEATURES_V2 = [
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    'idade_media', 'permanencia_media',
    'indice_atendimento_total_agua',
    'indice_coleta_esgoto',
    'indice_tratamento_esgoto',
    'indice_perda_distribuicao_agua',
    'MES_CMPT',
]
FEATURES_V2 = [f for f in FEATURES_V2 if f in df.columns]

df_modelo_v2 = df[FEATURES_V2 + ['houve_obito', 'ANO_CMPT']].dropna()

X_train_v2 = df_modelo_v2[df_modelo_v2['ANO_CMPT'].isin([2017,2018,2019])][FEATURES_V2]
y_train_v2 = df_modelo_v2[df_modelo_v2['ANO_CMPT'].isin([2017,2018,2019])]['houve_obito']
X_test_v2  = df_modelo_v2[df_modelo_v2['ANO_CMPT'].isin([2023,2024])][FEATURES_V2]
y_test_v2  = df_modelo_v2[df_modelo_v2['ANO_CMPT'].isin([2023,2024])]['houve_obito']

print(f'Features V2 ({len(FEATURES_V2)}): {FEATURES_V2}')
print(f'Treino: {len(X_train_v2):,} | Teste: {len(X_test_v2):,}')

from statsmodels.stats.outliers_influence import variance_inflation_factor

scaler_v2 = StandardScaler()
X_train_v2_sc = scaler_v2.fit_transform(X_train_v2)
X_test_v2_sc  = scaler_v2.transform(X_test_v2)

vif_v2 = pd.DataFrame({
    'feature': FEATURES_V2,
    'VIF': [variance_inflation_factor(X_train_v2_sc, i) for i in range(X_train_v2_sc.shape[1])]
}).sort_values('VIF', ascending=False)

print('VIF após correção:')
print(vif_v2.to_string(index=False))

model_v2 = LogisticRegression(
    class_weight='balanced',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)
model_v2.fit(X_train_v2_sc, y_train_v2)

y_pred_v2  = model_v2.predict(X_test_v2_sc)
y_proba_v2 = model_v2.predict_proba(X_test_v2_sc)[:, 1]

print('=' * 55)
print('AVALIAÇÃO V2 — APÓS REMOÇÃO DA MULTICOLINEARIDADE')
print('=' * 55)
print(classification_report(
    y_test_v2, y_pred_v2,
    target_names=['Sem Óbito (0)', 'Com Óbito (1)']
))
print(f'Macro F1 : {f1_score(y_test_v2, y_pred_v2, average="macro"):.4f}')
print(f'AUC-ROC  : {roc_auc_score(y_test_v2, y_proba_v2):.4f}')

coef_v2 = pd.DataFrame({
    'feature':     FEATURES_V2,
    'coeficiente': model_v2.coef_[0],
    'odds_ratio':  np.exp(model_v2.coef_[0])
}).sort_values('odds_ratio', ascending=False)

print('COEFICIENTES V2:')
print()
print(f'{"Feature":<42} {"Coef":>8} {"OR":>10}  Direção')
print('-' * 75)
for _, row in coef_v2.iterrows():
    direcao = '▲ aumenta risco' if row['odds_ratio'] > 1 else '▼ reduz risco'
    print(f'{row["feature"]:<42} {row["coeficiente"]:>8.4f} {row["odds_ratio"]:>10.4f}  {direcao}')

"""Verificando se o class_weight com balanced ou sem afetaria os resultados no projeto, uma vez que o recall de "sem óbito" fica baixo porque o balanced faz o modelo suspeitar mais e dar mais falsos positivos do que falsos negativos. Porém isso colocar none no class_weight apenas fez com que o modelo deixasse passar a maioria dos casos positivos verdadeiros, não dando um resultado tão aproximado da realidade."""

from sklearn.metrics import classification_report, f1_score, roc_auc_score

resultados_cw = {}

for cw, nome in [('balanced', 'Com class_weight=balanced'),
                 (None,       'Sem class_weight (padrão)')]:

    modelo_teste = LogisticRegression(
        class_weight=cw,
        solver='lbfgs',
        max_iter=1000,
        random_state=42
    )
    modelo_teste.fit(X_train_v2_sc, y_train_v2)
    y_pred_cw  = modelo_teste.predict(X_test_v2_sc)
    y_proba_cw = modelo_teste.predict_proba(X_test_v2_sc)[:, 1]

    rep = classification_report(y_test_v2,y_pred_cw,output_dict=True)
    resultados_cw[nome] = {
        'macro_f1':   f1_score(y_test_v2, y_pred_cw, average='macro'),
        'auc':        roc_auc_score(y_test_v2, y_proba_cw),
        'recall_1':   rep.get('1', {}).get('recall', 0),
        'precision_1':rep.get('1', {}).get('precision', 0),
    }

    print(f'\n── {nome} ──')
    print(classification_report(
        y_test_v2, y_pred_cw,
        target_names=['Sem Óbito (0)', 'Com Óbito (1)']
    ))

# Comparativo
print('=' * 65)
print('COMPARATIVO')
print('=' * 65)
print(f'{"Métrica":<22} {"Com balanced":>20} {"Sem balanced":>20}')
print('-' * 63)
for met, label in [('macro_f1','Macro F1'),('auc','AUC-ROC'),
                   ('recall_1','Recall (1)'),('precision_1','Precision (1)')]:
    v_com = resultados_cw['Com class_weight=balanced'][met]
    v_sem = resultados_cw['Sem class_weight (padrão)'][met]
    print(f'{label:<22} {v_com:>20.4f} {v_sem:>20.4f}')

"""# Agregação por ano

Resumo: funcionou melhor que a agregação mensal. Alinha a granularidade do target com a granularidade natural dos dados de saneamento (SNIS anual), elimina a contradição de rótulos causada por eventos raros em janelas mensais, e torna os zeros mais informativos — um zero anual representa 12 meses sem evento, não apenas um mês de janela curta.
"""

# ── AGREGA MUNICÍPIO × ANO ────────────────────────────────────────────────────
df_ano = (
    df.groupby(['MUNIC_RES', 'cod_macrorregiao', 'nome_macrorregiao', 'ANO_CMPT'])
    .agg(
        n_internacoes_drsai               = ('n_internacoes_drsai',               'sum'),
        n_obitos_drsai                    = ('n_obitos_drsai',                    'sum'),
        fecal_oral                        = ('fecal_oral',                        'sum'),
        leptospirose                      = ('leptospirose',                      'sum'),
        helmintiase                       = ('helmintiase',                       'sum'),
        arboviral                         = ('arboviral',                         'sum'),
        malaria                           = ('malaria',                           'sum'),
        idade_media                       = ('idade_media',                       'mean'),
        permanencia_media                 = ('permanencia_media',                 'mean'),
        indice_atendimento_total_agua     = ('indice_atendimento_total_agua',     'mean'),
        indice_coleta_esgoto              = ('indice_coleta_esgoto',              'mean'),
        indice_tratamento_esgoto          = ('indice_tratamento_esgoto',          'mean'),
        indice_perda_distribuicao_agua    = ('indice_perda_distribuicao_agua',    'mean'),
    )
    .reset_index()
)

# Target binário na nova granularidade
df_ano['houve_obito'] = (df_ano['n_obitos_drsai'] >= 1).astype(int)

print(f'Shape município × ano: {df_ano.shape[0]:,} linhas × {df_ano.shape[1]} colunas')
print(f'\nDistribuição do target:')
print(df_ano['houve_obito'].value_counts(normalize=True)
      .rename({0:'Sem óbito (0)', 1:'Com óbito (1)'}))
print(f'\nZeros: {(df_ano["houve_obito"]==0).mean():.1%}')

# ── SPLIT TEMPORAL ────────────────────────────────────────────────────────────
FEATURES_ANO = [f for f in [
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    'idade_media', 'permanencia_media',
    'indice_atendimento_total_agua',
    'indice_coleta_esgoto',
    'indice_tratamento_esgoto',
    'indice_perda_distribuicao_agua',
] if f in df_ano.columns]

df_ano_modelo = df_ano[FEATURES_ANO + ['houve_obito', 'ANO_CMPT']].dropna()

X_train_ano = df_ano_modelo[df_ano_modelo['ANO_CMPT'].isin([2017,2018,2019])][FEATURES_ANO]
y_train_ano = df_ano_modelo[df_ano_modelo['ANO_CMPT'].isin([2017,2018,2019])]['houve_obito']
X_test_ano  = df_ano_modelo[df_ano_modelo['ANO_CMPT'].isin([2023,2024])][FEATURES_ANO]
y_test_ano  = df_ano_modelo[df_ano_modelo['ANO_CMPT'].isin([2023,2024])]['houve_obito']

print(f'Treino (2017–2019): {len(X_train_ano):,} linhas')
print(f'Teste  (2023–2024): {len(X_test_ano):,} linhas')
print(f'\nDistribuição no treino:')
print(y_train_ano.value_counts(normalize=True).rename({0:'Sem óbito', 1:'Com óbito'}))
print(f'\nDistribuição no teste:')
print(y_test_ano.value_counts(normalize=True).rename({0:'Sem óbito', 1:'Com óbito'}))

"""Depois de treinar o modelo com agregação anual:
- Classe com óbito:
  - precisão de 0.83: quando o modelo diz "esse município não vai ter morte por drsai esse ano" ele está certo 83% das vezes.
  - recall de 0.70: de 6893 municípios sem óbito, ele acertou 70%, os outros 30% foram classificados como com risco sem ser

- Classe sem óbito
  - precisão de 0.51: de 100 munícipios que o modelo classificou como com risco, 51% tiveram mortes reais.
  - recall de 0.68: de 3.152 municípios com óbito real, o modelo detectou 68%.
"""

# ESCALONAMENTO + MODELO
scaler_ano = StandardScaler()
X_train_ano_sc = scaler_ano.fit_transform(X_train_ano)
X_test_ano_sc  = scaler_ano.transform(X_test_ano)

model_ano = LogisticRegression(
    class_weight='balanced',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)
model_ano.fit(X_train_ano_sc, y_train_ano)

y_pred_ano  = model_ano.predict(X_test_ano_sc)
y_proba_ano = model_ano.predict_proba(X_test_ano_sc)[:, 1]

print('=' * 55)
print('AVALIAÇÃO — MUNICÍPIO × ANO')
print('=' * 55)
print(classification_report(
    y_test_ano, y_pred_ano,
    target_names=['Sem Óbito (0)', 'Com Óbito (1)']
))
print(f'Macro F1 : {f1_score(y_test_ano, y_pred_ano, average="macro"):.4f}')
print(f'AUC-ROC  : {roc_auc_score(y_test_ano, y_proba_ano):.4f}')

"""No geral, a relação entre aumento de risco e os coeficientes ficou correto, porém para:

- indice_tratamento_esgoto      OR = 1.28  ▲  ← esperado: reduzir risco
- indice_atendimento_total_agua OR = 1.11  ▲  ← esperado: reduzir risco
- indice_coleta_esgoto          OR = 1.04  ▲  ← esperado: reduzir risco
"""

# ── COEFICIENTES ──────────────────────────────────────────────────────────────
coef_ano = pd.DataFrame({
    'feature':     FEATURES_ANO,
    'coeficiente': model_ano.coef_[0],
    'odds_ratio':  np.exp(model_ano.coef_[0])
}).sort_values('odds_ratio', ascending=False)

print('COEFICIENTES (município × ano):')
print()
print(f'{"Feature":<42} {"Coef":>8} {"OR":>10}  Direção')
print('-' * 72)
for _, row in coef_ano.iterrows():
    direcao = '▲ aumenta risco' if row['odds_ratio'] > 1 else '▼ reduz risco'
    print(f'{row["feature"]:<42} {row["coeficiente"]:>8.4f} {row["odds_ratio"]:>10.4f}  {direcao}')

# ── COMPARATIVO MÊS vs ANO ────────────────────────────────────────────────────
print('=' * 60)
print('COMPARATIVO DE GRANULARIDADE')
print('=' * 60)
print(f'{"Métrica":<20} {"Município × Mês":>18} {"Município × Ano":>18}')
print('-' * 58)

# Recupera métricas do modelo V2 (município × mês)
f1_mes = f1_score(y_test_v2, y_pred_v2, average='macro')
auc_mes = roc_auc_score(y_test_v2, y_proba_v2)
recall_mes = classification_report(y_test_v2, y_pred_v2, output_dict=True)['1']['recall']
prec_mes   = classification_report(y_test_v2, y_pred_v2, output_dict=True)['1']['precision']

f1_ano  = f1_score(y_test_ano, y_pred_ano, average='macro')
auc_ano = roc_auc_score(y_test_ano, y_proba_ano)
recall_ano = classification_report(y_test_ano, y_pred_ano, output_dict=True)['1']['recall']
prec_ano   = classification_report(y_test_ano, y_pred_ano, output_dict=True)['1']['precision']

print(f'{"Macro F1":<20} {f1_mes:>18.4f} {f1_ano:>18.4f}')
print(f'{"AUC-ROC":<20} {auc_mes:>18.4f} {auc_ano:>18.4f}')
print(f'{"Recall (óbito)":<20} {recall_mes:>18.4f} {recall_ano:>18.4f}')
print(f'{"Precision (óbito)":<20} {prec_mes:>18.4f} {prec_ano:>18.4f}')
print(f'{"Linhas treino":<20} {len(X_train_v2):>18,} {len(X_train_ano):>18,}')
print(f'{"Linhas teste":<20} {len(X_test_v2):>18,} {len(X_test_ano):>18,}')
print(f'{"% positivos treino":<20} {y_train_v2.mean():>18.1%} {y_train_ano.mean():>18.1%}')

"""# RANDOM FOREST

Afim de testar um segundo algoritmo para obter resultados mais próximos do esperado, utilizei a RF.

A random forest é uma combinação de várias árvores de decisão (uma floresta de árvores).\
[Datacamp - RF com Python](https://www.datacamp.com/tutorial/random-forests-classifier-python)\
[Random Forest - IBM](https://www.ibm.com/br-pt/think/topics/random-forest)

Escolhi ela pois:
- A RF pode fazer uma combinação de features, o que pode explicar melhor a chance de óbito
- A RF tem robustez a outliers e a distribuições assimétricas
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance

# ── RANDOM FOREST — município × ano ──────────────────────────────────────────
# Mesmas features e split do modelo de ano já treinado
# n_estimators=200: 200 árvores — bom equilíbrio entre desempenho e custo
# class_weight='balanced': mantém o mesmo tratamento de imbalance
# max_depth=10: limita profundidade para evitar overfitting
# random_state=42: reprodutibilidade

rf_model = RandomForestClassifier(
    n_estimators=400,
    max_depth=10,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1       # usa todos os núcleos disponíveis
)

rf_model.fit(X_train_ano_sc, y_train_ano)

y_pred_rf  = rf_model.predict(X_test_ano_sc)
y_proba_rf = rf_model.predict_proba(X_test_ano_sc)[:, 1]

print('✅ Random Forest treinado.')
print(f'   Features: {len(FEATURES_ANO)}')
print(f'   Árvores : {rf_model.n_estimators}')

print('=' * 55)
print('AVALIAÇÃO — RANDOM FOREST (município × ano)')
print('=' * 55)
print(classification_report(
    y_test_ano, y_pred_rf,
    target_names=['Sem Óbito (0)', 'Com Óbito (1)']
))

f1_rf  = f1_score(y_test_ano, y_pred_rf, average='macro')
auc_rf = roc_auc_score(y_test_ano, y_proba_rf)

print(f'Macro F1 : {f1_rf:.4f}')
print(f'AUC-ROC  : {auc_rf:.4f}')

# ── IMPORTÂNCIA DE FEATURES (Gini Impurity) ───────────────────────────────────
# Diferente do odds ratio da RL, a importância do RF captura
# contribuições não-lineares e interações entre features

importancia_df = pd.DataFrame({
    'feature':    FEATURES_ANO,
    'importancia': rf_model.feature_importances_
}).sort_values('importancia', ascending=False)

print('IMPORTÂNCIA DAS FEATURES (Random Forest — Gini):')
print()
print(f'{"Feature":<42} {"Importância":>12}  {"Barra"}')
print('-' * 75)
for _, row in importancia_df.iterrows():
    barra = '█' * int(row['importancia'] * 200)
    print(f'{row["feature"]:<42} {row["importancia"]:>12.4f}  {barra}')

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# Painel 1 — Curva ROC sobreposta
RocCurveDisplay.from_predictions(
    y_test_ano, y_proba_ano, ax=axes[0],
    name=f'Regressão Logística (AUC={roc_auc_score(y_test_ano, y_proba_ano):.3f})',
    color='#2471A3'
)
RocCurveDisplay.from_predictions(
    y_test_ano, y_proba_rf, ax=axes[0],
    name=f'Random Forest (AUC={auc_rf:.3f})',
    color='#E74C3C'
)
axes[0].plot([0,1],[0,1], 'k--', linewidth=1, label='Aleatório (AUC=0.500)')
axes[0].set_title('Curva ROC — RL vs RF\n(Município × Ano)', fontweight='bold')
axes[0].legend(fontsize=9)

# ── Painel 2 — Importância das features RF vs coeficientes RL normalizados ───
coef_abs = coef_ano.copy()
coef_abs['coef_norm'] = coef_abs['coeficiente'].abs() / coef_abs['coeficiente'].abs().sum()
coef_abs = coef_abs.set_index('feature')['coef_norm']

imp_rf = importancia_df.set_index('feature')['importancia']

feats_comuns = [f for f in FEATURES_ANO]
x = np.arange(len(feats_comuns))
w = 0.35

axes[1].barh(x + w/2, [coef_abs.get(f, 0) for f in feats_comuns],
             height=w, label='RL |coef| norm.', color='#2471A3', alpha=0.8)
axes[1].barh(x - w/2, [imp_rf.get(f, 0) for f in feats_comuns],
             height=w, label='RF importância', color='#E74C3C', alpha=0.8)
axes[1].set_yticks(x)
axes[1].set_yticklabels(feats_comuns, fontsize=9)
axes[1].set_xlabel('Contribuição relativa')
axes[1].set_title('Importância das Features — RL vs RF\n(Município × Ano)', fontweight='bold')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig(PATH_OUTPUTS + 'mineracao_03_roc_e_features_rl_vs_rf.png', dpi=150, bbox_inches='tight')
plt.show()
print('Salvo: mineracao_03_roc_e_features_rl_vs_rf.png')

print('=' * 80)
print('COMPARATIVO FINAL — TODOS OS MODELOS')
print('=' * 80)

# Recupera métricas de todos os modelos anteriores
def get_metrics(y_true, y_pred, y_proba):
    rep = classification_report(y_true, y_pred, output_dict=True)
    return {
        'macro_f1':   f1_score(y_true, y_pred, average='macro'),
        'auc':        roc_auc_score(y_true, y_proba),
        'recall_1':   rep['1']['recall'],
        'precision_1':rep['1']['precision'],
    }

modelos = {
    'RL  Mês  (houve_obito)': get_metrics(y_test_v2,    y_pred_v2,    y_proba_v2),
    'RL  Ano  (houve_obito)': get_metrics(y_test_ano,   y_pred_ano,   y_proba_ano),
    'RF  Ano  (houve_obito)': get_metrics(y_test_ano,   y_pred_rf,    y_proba_rf),
}

metricas = ['macro_f1', 'auc', 'recall_1', 'precision_1']
labels   = ['Macro F1', 'AUC-ROC', 'Recall (1)', 'Precision (1)']

print(f'{"Modelo":<28}', end='')
for l in labels:
    print(f'{l:>14}', end='')
print()
print('-' * 84)

for nome, m in modelos.items():
    print(f'{nome:<28}', end='')
    for met in metricas:
        print(f'{m[met]:>14.4f}', end='')
    print()

print()
print('SNIS — sinais do RF vs RL (município × ano):')
print()
cols_snis = [c for c in FEATURES_ANO if 'indice' in c]
print(f'{"Feature":<42} {"OR  (RL)":>10} {"Imp. (RF)":>12}')
print('-' * 66)
for feat in cols_snis:
    or_rl = coef_ano[coef_ano['feature']==feat]['odds_ratio'].values[0]
    imp   = importancia_df[importancia_df['feature']==feat]['importancia'].values[0]
    print(f'{feat:<42} {or_rl:>10.3f} {imp:>12.4f}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── RL Município × Ano ────────────────────────────────────────────────────────
cm_rl = confusion_matrix(y_test_ano, y_pred_ano)
disp_rl = ConfusionMatrixDisplay(cm_rl, display_labels=['Sem Óbito', 'Com Óbito'])
disp_rl.plot(ax=axes[0], cmap='Blues', colorbar=False)
axes[0].set_title(
    f'Regressão Logística — Município × Ano\n'
    f'Macro F1={f1_score(y_test_ano, y_pred_ano, average="macro"):.3f}  '
    f'AUC={roc_auc_score(y_test_ano, y_proba_ano):.3f}',
    fontweight='bold'
)

# ── Random Forest Município × Ano ─────────────────────────────────────────────
cm_rf = confusion_matrix(y_test_ano, y_pred_rf)
disp_rf = ConfusionMatrixDisplay(cm_rf, display_labels=['Sem Óbito', 'Com Óbito'])
disp_rf.plot(ax=axes[1], cmap='Reds', colorbar=False)
axes[1].set_title(
    f'Random Forest — Município × Ano\n'
    f'Macro F1={f1_score(y_test_ano, y_pred_rf, average="macro"):.3f}  '
    f'AUC={roc_auc_score(y_test_ano, y_proba_rf):.3f}',
    fontweight='bold'
)

plt.suptitle('Matrizes de Confusão — Teste 2023–2024', fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(PATH_OUTPUTS + 'mineracao_05_confusao_rl_vs_rf.png', dpi=150, bbox_inches='tight')
plt.show()
print('Salvo: mineracao_05_confusao_rl_vs_rf.png')

print('=' * 60)
print('LEITURA DAS MATRIZES DE CONFUSÃO — Teste 2023–2024')
print('=' * 60)

for nome, cm, y_pred, y_proba in [
    ('Regressão Logística (Ano)', cm_rl, y_pred_ano, y_proba_ano),
    ('Random Forest      (Ano)', cm_rf, y_pred_rf,  y_proba_rf),
]:
    tn, fp, fn, tp = cm.ravel()
    total    = tn + fp + fn + tp
    total_0  = tn + fp
    total_1  = fn + tp

    print(f'\n── {nome} ──')
    print(f'  VN (sem óbito, previsto correto) : {tn:>6,}  ({100*tn/total_0:.1f}% dos negativos reais)')
    print(f'  FP (sem óbito, previsto risco)   : {fp:>6,}  ({100*fp/total_0:.1f}% dos negativos reais)')
    print(f'  FN (com óbito, NÃO detectado)    : {fn:>6,}  ({100*fn/total_1:.1f}% dos positivos reais) ← crítico')
    print(f'  VP (com óbito, detectado)        : {tp:>6,}  ({100*tp/total_1:.1f}% dos positivos reais)')
    print(f'  Alarmes corretos (Precision)     : {100*tp/(tp+fp):.1f}%')
    print(f'  Casos capturados (Recall)        : {100*tp/(tp+fn):.1f}%')

"""# Conclusão — Notebook 06: Mineração e Classificação DRSAI

Este notebook documentou o processo completo de mineração de dados seguindo
o framework **CRISP-DM**, desde a formulação do problema até a comparação
de modelos.

## 1. Decisões Metodológicas

### 1.1 Escolha da granularidade

Foram testadas duas granularidades temporais:

| Granularidade | Linhas treino | % positivos | Observação |
|---|---|---|---|
| Município × Mês | 102.294 | 5,7% | Imbalance severo |
| Município × Ano | 14.218 | 24,2% | Balanceamento adequado |

**Decisão:** município × ano como granularidade principal do modelo,
pois o imbalance de 93.5% de zeros no nível mensal gerava distribuição
degenerada, qualquer threshold entre 0 e 1 colapsava as classes
médio/alto, inviabilizando a separação.

### 1.2 Formulação do target

**Target adotado:** `houve_obito` é uma variável binária derivada de
`n_obitos_drsai >= 1`.

- `0` = nenhum óbito DRSAI registrado no município no ano
- `1` = pelo menos um óbito DRSAI registrado no município no ano

### 1.3 Split temporal

| Conjunto | Período | Linhas | Justificativa |
|---|---|---|---|
| Treino | 2017–2019 | 14.218 | Padrão histórico pré-pandemia |
| **Excluído** | 2020–2022 | — | Choque COVID distorce padrões |
| Teste | 2023–2024 | 10.044 | Avaliação em dados futuros |

Este é um **split temporal** pois simula o uso real do modelo, onde se treina no passado para prever o futuro.

### 1.4 Tratamento do imbalance

Aplicado `class_weight='balanced'` em ambos os modelos.
O parâmetro ajusta automaticamente os pesos das classes inversamente
proporcionais à sua frequência, penalizando mais os erros na classe
minoritária (municípios com óbito).

### 1.5 Features selecionadas

```python
FEATURES_ANO = [
    # Perfil epidemiológico anual
    'fecal_oral', 'leptospirose', 'helmintiase', 'arboviral', 'malaria',
    # Perfil clínico dos internados
    'idade_media', 'permanencia_media',
    # Indicadores de saneamento municipal (SNIS)
    'indice_atendimento_total_agua',
    'indice_coleta_esgoto',
    'indice_tratamento_esgoto',
    'indice_perda_distribuicao_agua',
]
```

**Removidas por multicolinearidade:**
- `n_internacoes_drsai`: soma linear das categorias (r=0.93 com fecal_oral, VIF=∞)
- `indice_esgotamento_agua_consumida`: redundante com coleta + tratamento (r=0.74/0.80)

## 2. Resultados dos Modelos

### 2.1 Comparativo geral

| Modelo | Macro F1 | AUC-ROC | Recall (1) | Precision (1) |
|---|---|---|---|---|
| RL — Município × Mês | 0.522 | 0.774 | 74.4% | 16.2% |
| RL — Município × Ano | 0.672 | 0.768 | 68.2% | 51.1% |
| **RF — Município × Ano** | **0.705** | **0.802** | 61.2% | **58.7%** |

### 2.2 Análise das matrizes de confusão (Teste 2023–2024)

#### Regressão Logística — Município × Ano

| | Previsto: Sem Óbito | Previsto: Com Óbito |
|---|---|---|
| **Real: Sem Óbito** | 4.830 ✅ (VN) | 2.062 ❌ (FP) |
| **Real: Com Óbito** | 1.001 ❌ (FN) | 2.151 ✅ (VP) |

- Detecta **68.2%** dos municípios com óbito real
- Gera **2.062 falsos alarmes** (29.9% dos negativos reais)

#### Random Forest — Município × Ano

| | Previsto: Sem Óbito | Previsto: Com Óbito |
|---|---|---|
| **Real: Sem Óbito** | 5.534 ✅ (VN) | 1.358 ❌ (FP) |
| **Real: Com Óbito** | 1.223 ❌ (FN) | 1.929 ✅ (VP) |

- Detecta **61.2%** dos municípios com óbito real
- Gera **1.358 falsos alarmes** (19.7% dos negativos reais)

### 2.3 Trade-off entre os modelos

O par RL × RF revela um **trade-off clássico em saúde pública**:

| Critério | Melhor modelo | Magnitude |
|---|---|---|
| Não perder casos de risco | **RL** | +222 casos detectados |
| Economizar recursos de vigilância | **RF** | −704 falsos alarmes |
| Discriminação geral (AUC) | **RF** | +0.034 |
| Balanceamento das métricas (F1) | **RF** | +0.033 |

**Interpretação operacional:**
- Se o gestor tem **recursos limitados** e precisa priorizar → **RF**
  (58.7% dos alarmes são corretos)
- Se o objetivo é **vigilância ampla** sem perder casos → **RL**
  (captura 222 casos adicionais)

## 4. Limitações e Trabalhos Futuros

### 4.1 Limitações do estudo

**Limitação 1 — Cobertura do SIH-SUS**
O SIH registra apenas óbitos intra-hospitalares. Mortes domiciliares,
em UPAs ou no trajeto ao hospital não aparecem nos dados. Isso
subestima a mortalidade real por DRSAI, especialmente em municípios
de baixa cobertura hospitalar.

**Limitação 2 — Viés de notificação**
Como discutido na Seção 3.2, municípios com melhor infraestrutura
tendem a registrar mais óbitos. Esse viés afeta a interpretabilidade
dos coeficientes dos indicadores de saneamento.

**Limitação 3 — Defasagem temporal do SNIS**
Os indicadores SNIS são coletados anualmente com defasagem de até
2 anos. O join pelo ano de competência pode não capturar mudanças
recentes na infraestrutura de saneamento.

**Limitação 4 — Exclusão do período COVID**
Os anos 2020–2022 foram excluídos para evitar distorção nos padrões.
Isso reduz o volume de dados de treino e pode não capturar mudanças
estruturais no perfil de DRSAI pós-pandemia.

### 4.2 Trabalhos futuros

- Incluir proxy de **capacidade de notificação municipal** para isolar
  viés de infraestrutura hospitalar
- Testar **Regressão de Poisson** modelando diretamente `n_obitos_drsai`
  como variável de contagem — abordagem canônica em epidemiologia
- Incluir dados **SINAN** (notificações) como features antecedentes,
  criando defasagem temporal explícita entre notificação e óbito
- Estender para **doenças vetoriais** (dengue, zika, chikungunya)
  atualmente fora do escopo
- Ajustar pela **taxa por habitante** em vez de contagens absolutas
  para controlar o efeito de tamanho do município## 3. Interpretação das Features

### 3.1 Preditores mais importantes (Random Forest — Gini Impurity)

| Rank | Feature | Importância | Interpretação |
|---|---|---|---|
| 1 | `fecal_oral` | 31.2% | Transmissão hídrica é o sinal dominante de risco |
| 2 | `permanencia_media` | 13.2% | Internações longas indicam casos graves |
| 3 | `idade_media` | 12.9% | Pacientes mais velhos têm menor tolerância à desidratação |
| 4 | `arboviral` | 11.7% | Arboviroses sinalizam ambiente propício a vetores |
| 5 | `indice_perda_distribuicao_agua` | 7.1% | Perdas na rede indicam pressão baixa e contaminação |

### 3.2 Achado: paradoxo dos indicadores de saneamento

Os indicadores SNIS de cobertura (água e esgoto) apresentaram
**odds ratios > 1 na Regressão Logística** — contrários ao esperado.

**Hipótese mais provável: viés de notificação**

Municípios com melhor saneamento também possuem melhor infraestrutura
hospitalar e maior capacidade de registro administrativo. (?)

**Evidências que sustentam essa hipótese:**
- O diagnóstico de multicolinearidade foi descartado (VIF < 1.5 após correção)
- Correlação entre saneamento e volume de internações é próxima de zero
  (r < 0.04), descartando viés de tamanho de município
- Os sinais se mantiveram após remoção de todas as variáveis redundantes

**Implicação metodológica:** modelos futuros deveriam incluir uma
proxy de capacidade de notificação municipal (ex: cobertura de
estabelecimentos SUS por habitante) para isolar o efeito real
do saneamento.

### 3.3 Preditores com sinal correto

`indice_perda_distribuicao_agua` (OR=1.17 na RL, 7.1% de importância
no RF) foi o único indicador SNIS com interpretação direta: perdas na
rede de distribuição implicam pressão baixa, pontos de entrada de
contaminação e abastecimento irregular — condições que aumentam
exposição a agentes patogênicos das DRSAI.
"""

# ── EXEMPLO DE USO DO MODELO ──────────────────────────────────────────────────
# Simula como o modelo seria usado na prática:
# dado um município com determinado perfil, qual a probabilidade de óbito?

exemplo = pd.DataFrame([{
    'fecal_oral':                      50,    # internações fecal-oral no ano
    'leptospirose':                     2,
    'helmintiase':                      3,
    'arboviral':                       10,
    'malaria':                          0,
    'idade_media':                     45.0,  # idade média dos internados
    'permanencia_media':                4.5,  # dias médios de internação
    'indice_atendimento_total_agua':   60.0,  # 60% de cobertura de água
    'indice_coleta_esgoto':            20.0,  # 20% de coleta de esgoto
    'indice_tratamento_esgoto':        15.0,
    'indice_perda_distribuicao_agua':  40.0,  # 40% de perdas na rede
}])

exemplo_sc = scaler_ano.transform(exemplo)
prob = rf_model.predict_proba(exemplo_sc)[0][1]
pred = rf_model.predict(exemplo_sc)[0]

print('EXEMPLO DE PREDIÇÃO — MUNICÍPIO HIPOTÉTICO')
print('=' * 50)
print(f'  Probabilidade de óbito DRSAI : {prob:.1%}')
print(f'  Classificação                : {"⚠️  RISCO (Com Óbito)" if pred == 1 else "✅ Sem Risco"}')
print()
print('  Perfil do município:')
for col, val in exemplo.iloc[0].items():
    print(f'    {col:<40}: {val}')

# ── EXEMPLO DE PREDIÇÃO — REGRESSÃO LOGÍSTICA (Município × Ano) ───────────────
# Mesmo município hipotético do exemplo do RF para facilitar a comparação

exemplo_rl = pd.DataFrame([{
    'fecal_oral':                      50,    # internações fecal-oral no ano
    'leptospirose':                     2,
    'helmintiase':                      3,
    'arboviral':                       10,
    'malaria':                          0,
    'idade_media':                     45.0,  # idade média dos internados
    'permanencia_media':                4.5,  # dias médios de internação
    'indice_atendimento_total_agua':   60.0,  # 60% de cobertura de água
    'indice_coleta_esgoto':            20.0,  # 20% de coleta de esgoto
    'indice_tratamento_esgoto':        15.0,
    'indice_perda_distribuicao_agua':  40.0,  # 40% de perdas na rede
}])

exemplo_rl_sc = scaler_ano.transform(exemplo_rl)
prob_rl = model_ano.predict_proba(exemplo_rl_sc)[0][1]
pred_rl = model_ano.predict(exemplo_rl_sc)[0]

print('EXEMPLO DE PREDIÇÃO — MUNICÍPIO HIPOTÉTICO')
print('=' * 55)
print()
print('PERFIL DO MUNICÍPIO:')
print(f'  {"fecal_oral":<42}: 50 internações/ano')
print(f'  {"leptospirose":<42}: 2 internações/ano')
print(f'  {"helmintiase":<42}: 3 internações/ano')
print(f'  {"arboviral":<42}: 10 internações/ano')
print(f'  {"malaria":<42}: 0 internações/ano')
print(f'  {"idade_media":<42}: 45.0 anos')
print(f'  {"permanencia_media":<42}: 4.5 dias')
print(f'  {"indice_atendimento_total_agua":<42}: 60.0%')
print(f'  {"indice_coleta_esgoto":<42}: 20.0%')
print(f'  {"indice_tratamento_esgoto":<42}: 15.0%')
print(f'  {"indice_perda_distribuicao_agua":<42}: 40.0%')
print()
print('─' * 55)
print()
print('RESULTADO — REGRESSÃO LOGÍSTICA (Município × Ano):')
print(f'  Probabilidade de óbito DRSAI : {prob_rl:.1%}')
print(f'  Classificação                : {"⚠️  RISCO (Com Óbito)" if pred_rl == 1 else "✅ Sem Risco"}')
print()
print('─' * 55)
print()

# comparativo rf e rl
exemplo_rf_sc = scaler_ano.transform(exemplo_rl)  # mesmo scaler
prob_rf = rf_model.predict_proba(exemplo_rf_sc)[0][1]
pred_rf = rf_model.predict(exemplo_rf_sc)[0]

print('COMPARATIVO — MESMO MUNICÍPIO, DOIS MODELOS:')
print()
print(f'  {"Modelo":<30} {"Probabilidade":>15} {"Classificação":>20}')
print('  ' + '-' * 67)
print(f'  {"Regressão Logística":<30} {prob_rl:>14.1%} '
      f'{"⚠️  Com Risco" if pred_rl == 1 else "✅ Sem Risco":>20}')
print(f'  {"Random Forest":<30} {prob_rf:>14.1%} '
      f'{"⚠️  Com Risco" if pred_rf == 1 else "✅ Sem Risco":>20}')
print()
print('─' * 55)
print()
print('INTERPRETAÇÃO:')
print(f'  A RL calcula uma combinação linear dos coeficientes')
print(f'  e passa pela função sigmoid para gerar {prob_rl:.1%}.')
print()
print(f'  O RF consulta 200 árvores de decisão e conta os votos.')
print(f'  Resultado: {prob_rf*200:.0f} de 200 árvores votaram COM ÓBITO → {prob_rf:.1%}.')

"""# PREDIÇÃO DO RISCO DE MUNICÍPIOS"""

MUNICIPIO_BUSCAR = '530010'   # string, não inteiro
ANO_PREDIZER     = 2024

dados_municipio = df[
    (df['MUNIC_RES'].astype(str) == MUNICIPIO_BUSCAR) &
    (df['ANO_CMPT']  == ANO_PREDIZER)
]

print(f'Município: {MUNICIPIO_BUSCAR} — DISTRITO FEDERAL')
print(f'Registros encontrados: {len(dados_municipio)} meses')
print()
print(dados_municipio[['ANO_CMPT', 'MES_CMPT', 'n_internacoes_drsai',
                        'n_obitos_drsai', 'fecal_oral', 'leptospirose',
                        'helmintiase', 'arboviral', 'malaria']].to_string(index=False))

# ── AGREGA O ANO INTEIRO E PREDIZ ─────────────────────────────────────────────
perfil_real = pd.DataFrame([{
    'fecal_oral':                         dados_municipio['fecal_oral'].sum(),
    'leptospirose':                        dados_municipio['leptospirose'].sum(),
    'helmintiase':                         dados_municipio['helmintiase'].sum(),
    'arboviral':                           dados_municipio['arboviral'].sum(),
    'malaria':                             dados_municipio['malaria'].sum(),
    'idade_media':                         dados_municipio['idade_media'].mean(),
    'permanencia_media':                   dados_municipio['permanencia_media'].mean(),
    'indice_atendimento_total_agua':       dados_municipio['indice_atendimento_total_agua'].mean(),
    'indice_coleta_esgoto':                dados_municipio['indice_coleta_esgoto'].mean(),
    'indice_tratamento_esgoto':            dados_municipio['indice_tratamento_esgoto'].mean(),
    'indice_perda_distribuicao_agua':      dados_municipio['indice_perda_distribuicao_agua'].mean(),
}])

# Verifica nulos
nulos = perfil_real.isna().sum().sum()
if nulos > 0:
    print(f'⚠️  {nulos} valores nulos — preenchendo com mediana do dataset')
    for col in perfil_real.columns:
        if perfil_real[col].isna().any():
            perfil_real[col] = df[col].median()

# Escalonamento e predição
perfil_sc = scaler_ano.transform(perfil_real)

prob_rl  = model_ano.predict_proba(perfil_sc)[0][1]
pred_rl  = model_ano.predict(perfil_sc)[0]
prob_rf  = rf_model.predict_proba(perfil_sc)[0][1]
pred_rf  = rf_model.predict(perfil_sc)[0]
votos_rf = int(prob_rf * 200)

obitos_reais = dados_municipio['n_obitos_drsai'].sum()

print('=' * 60)
print(f'PREDIÇÃO — DISTRITO FEDERAL | ANO {ANO_PREDIZER}')
print('=' * 60)
print()
print('PERFIL REAL DO MUNICÍPIO:')
for col in FEATURES_ANO:
    val = perfil_real[col].values[0]
    if 'indice' in col:
        print(f'  {col:<42}: {val:.1f}%')
    elif col in ['idade_media', 'permanencia_media']:
        print(f'  {col:<42}: {val:.1f}')
    else:
        print(f'  {col:<42}: {val:.0f} internações/ano')

print()
print('─' * 60)
print()
print('PREDIÇÕES:')
print(f'  {"Modelo":<30} {"Probabilidade":>15} {"Classificação"}')
print('  ' + '-' * 58)
print(f'  {"Regressão Logística":<30} {prob_rl:>14.1%}   '
      f'{"⚠️  COM RISCO" if pred_rl == 1 else "✅ SEM RISCO"}')
print(f'  {"Random Forest":<30} {prob_rf:>14.1%}   '
      f'{"⚠️  COM RISCO" if pred_rf == 1 else "✅ SEM RISCO"}')
print(f'  {"(votos RF)":<30} {votos_rf:>12} /200 árvores')
print()
print('─' * 60)
print()
print('VALIDAÇÃO (dado real):')
print(f'  Óbitos DRSAI reais em {ANO_PREDIZER} : {obitos_reais:.0f}')
print(f'  Target real                    : '
      f'{"1 — COM ÓBITO ⚠️" if obitos_reais >= 1 else "0 — SEM ÓBITO ✅"}')

acerto_rl = (pred_rl == (1 if obitos_reais >= 1 else 0))
acerto_rf = (pred_rf == (1 if obitos_reais >= 1 else 0))
print()
print(f'  RL acertou: {"✅ SIM" if acerto_rl else "❌ NÃO"}')
print(f'  RF acertou: {"✅ SIM" if acerto_rf else "❌ NÃO"}')

# ── PREDIÇÃO EM LOTE — top municípios por probabilidade de risco ──────────────
ANO_LOTE = 2024

df_lote = (
    df[df['ANO_CMPT'] == ANO_LOTE]
    .groupby(['MUNIC_RES', 'nome_macrorregiao'])
    .agg(
        fecal_oral                        = ('fecal_oral',                        'sum'),
        leptospirose                      = ('leptospirose',                      'sum'),
        helmintiase                       = ('helmintiase',                       'sum'),
        arboviral                         = ('arboviral',                         'sum'),
        malaria                           = ('malaria',                           'sum'),
        idade_media                       = ('idade_media',                       'mean'),
        permanencia_media                 = ('permanencia_media',                 'mean'),
        indice_atendimento_total_agua     = ('indice_atendimento_total_agua',     'mean'),
        indice_coleta_esgoto              = ('indice_coleta_esgoto',              'mean'),
        indice_tratamento_esgoto          = ('indice_tratamento_esgoto',          'mean'),
        indice_perda_distribuicao_agua    = ('indice_perda_distribuicao_agua',    'mean'),
        obitos_reais                      = ('n_obitos_drsai',                    'sum'),
    )
    .reset_index()
    .dropna(subset=FEATURES_ANO)
)

# Escalonamento e predição em lote
X_lote    = df_lote[FEATURES_ANO]
X_lote_sc = scaler_ano.transform(X_lote)

df_lote['prob_rf']   = rf_model.predict_proba(X_lote_sc)[:, 1]
df_lote['prob_rl']   = model_ano.predict_proba(X_lote_sc)[:, 1]
df_lote['pred_rf']   = rf_model.predict(X_lote_sc)
df_lote['pred_rl']   = model_ano.predict(X_lote_sc)

target_real = (df_lote['obitos_reais'] >= 1).astype(int)
df_lote['acerto_rf'] = (df_lote['pred_rf'] == target_real)
df_lote['acerto_rl'] = (df_lote['pred_rl'] == target_real)

# Top 20 municípios com maior risco previsto pelo RF
top20 = df_lote.nlargest(20, 'prob_rf')[
    ['MUNIC_RES', 'nome_macrorregiao', 'fecal_oral',
     'prob_rl', 'prob_rf', 'obitos_reais', 'acerto_rl', 'acerto_rf']
].reset_index(drop=True)

print(f'TOP 20 MUNICÍPIOS DE MAIOR RISCO PREVISTO — {ANO_LOTE}')
print(f'(ordenado por probabilidade RF)')
print()
print(f'{"#":>3} {"Município":>10} {"Macrorregião":<28} '
      f'{"fecal_oral":>11} {"P(RL)":>7} {"P(RF)":>7} '
      f'{"Óbitos reais":>13} {"Ac. RL":>8} {"Ac. RF":>8}')
print('-' * 103)

for i, row in top20.iterrows():
    ac_rl = '✅' if row['acerto_rl'] else '❌'
    ac_rf = '✅' if row['acerto_rf'] else '❌'
    print(f'{i+1:>3} {row["MUNIC_RES"]:>10} {str(row["nome_macrorregiao"])[:27]:<28} '
          f'{row["fecal_oral"]:>11.0f} {row["prob_rl"]:>7.1%} {row["prob_rf"]:>7.1%} '
          f'{row["obitos_reais"]:>13.0f} {ac_rl:>8} {ac_rf:>8}')

print()
# Acurácia comparativa dos dois modelos
ac_rf_geral = df_lote['acerto_rf'].mean()
ac_rl_geral = df_lote['acerto_rl'].mean()
n_rf = df_lote['acerto_rf'].sum()
n_rl = df_lote['acerto_rl'].sum()
total = len(df_lote)

print(f'{"Acurácia geral no lote " + str(ANO_LOTE) + ":":<35} {"RL":>5}  {"RF":>5}')
print(f'{"  Acurácia":<35} {ac_rl_geral:>5.1%}  {ac_rf_geral:>5.1%}')
print(f'{"  Acertos absolutos":<35} {n_rl:>5,}  {n_rf:>5,}  (de {total:,} municípios)')